### ISSUE TITLE
Can an AutoParcelGson class be extended?

### ISSUE THREAD

**Issue by jwburnside** [evant/auto-parcel-gson#11]
In my case, both classes have the @AutoParcelGson annotation. When I attempt to extend an AutoParcelGson class, I get an error: 
**One AutoParcelGson class may not extend another.**
Is there a way to extend a class?

**Comment by evant** [comment]
This is a [feature](https://github.com/google/auto/blob/master/value/userguide/howto.md#inherit) not a bug :wink:

If you have common fields, you can put them in an interface that both implementations implement.

**Comment by jwburnside** [comment]
Ah yes, of course, thanks!
