### ISSUE TITLE
Support gson v2.5.

### ISSUE THREAD

**Issue by johnkil** [evant/auto-parcel-gson#6]

**Comment by evant** [comment]
What is there to support? Are you having trouble depending on 2.5?

**Comment by johnkil** [comment]
No, just update version of dependency `compile 'com.google.code.gson:gson:2.5'`.

**Comment by evant** [comment]
I fail to understand the issue. There is no reason to update the transitive dependency if there aren't any incompatibilities. You should be defining what version of gson you are depending on in your app anyway.

**Comment by johnkil** [comment]
ок, actually you're right.
