### ISSUE TITLE
Generated class is package-private

### ISSUE THREAD

**Issue by Kritarie** [evant/auto-parcel-gson#7]
This includes the generated builder. Is there a reason for this? I believe it should be public.

**Comment by evant** [comment]
This is a design decision of AutoValue, I assume because the abstract class should be the only one that has knowledge of it's implementation. From the [docs](https://github.com/google/auto/tree/master/value):

>  Usage is API-invisible (callers cannot become dependent on your choice to use it, or generally even tell the difference)

I'm not going to change this.

**Comment by Kritarie** [comment]
I agree with that decision, however, AutoValue has no need to support Gson TypeAdapters for the subclass implementation. Currently the AutoParcelGsonTypeAdapterFactory delegates the abstract type to its implementation using reflection, but there's no way to have Gson use something other than the ReflectiveTypeAdapter for that type outside of defining the TypeAdapter in the same package as the abstract value class.

**Comment by evant** [comment]
Actually the ReflectiveTypeAdapter has another problem in that is bypasses autovalue's null checks. Ideally, a TypeAdapter should be generated for each class which calls it's constructor or builder. This just hasn't been implemented because it's more complex.
