### ISSUE TITLE
TypeAdapterFactory does not support ParameterizedType

### ISSUE THREAD

**Issue by Kritarie** [evant/auto-parcel-gson#8]
Class.forName() returns a non-parameterized type, so if I want to register another TypeAdapterFactory for my generic generated type, Gson can't get type information from it, and so the TypeToken's type will not be an instance of ParameterizedType.

For a little more context, this is the TypeAdapterFactory I have:

```
@Override
@SuppressWarnings("unchecked")
public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> token) {
    if (PagingResponse.class.isAssignableFrom(token.getRawType())) {
        Type type = token.getType();
        if (type instanceof ParameterizedType) {
            ParameterizedType param = (ParameterizedType) type;
            Type[] instantiated = param.getActualTypeArguments();
            if (instantiated.length == 1 && Person.class.isAssignableFrom(TypeToken.get(instantiated[0]).getRawType())) {
                return (TypeAdapter<T>) gson.getAdapter(new TypeToken<PagingResponse<Person>>(){});
            }
        }
    }
    return null;
}
```

The second condition, type instanceof ParameterizedType, is always false for type AutoParcelGson_PagingResponse even though it has a generic type.

**Comment by Kritarie** [comment]
Looks like the generics issue is fixed, but now the generated subclass' fields are not including @SerializedName annotations. The overriden methods are annotated, but since the factory delegates to a ReflectiveTypeAdapter, they are ignored.

**Comment by evant** [comment]
Are you using `@auto.parcelgson.gson.annotations.SerializedName` instead of `@com.google.gson.annotations.SerializedName`? They added support for putting the gson one methods in gson 2.4, which unfortunately means they won't be copied over to the fields like this lib's one. Am planning on making it so either one is valid, or even remove this lib's version.

**Comment by Kritarie** [comment]
Ahh, yep that was the issue.
